apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-client
  template:
    metadata:
      labels:
        app: manager-client
    spec:
      containers:
      - name: manager-client
        image: your-docker-repo/manager-client:latest
        command: ["/app/manager_client"]