apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      otlphttp/logs:
        endpoint: http://loki.loki.svc.cluster.local/otlp
        tls:
          insecure: true
      otlp/traces:
        endpoint: http://tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: ${MY_POD_IP}:8889
        send_timestamps: true
        metric_expiration: 30m
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/traces]

        metrics:
          receivers: [otlp, prometheus]
          exporters: [prometheus]

        logs:
          receivers: [otlp]
          exporters: [otlphttp/logs]
