apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      otlphttp/logs:
        endpoint: http://loki.loki.svc.cluster.local/otlp
        tls:
          insecure: true
      otlp/traces:
        endpoint: http://tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
        sending_queue:
          enabled: true
          queue_size: 10000
      prometheus:
        endpoint: 0.0.0.0:9464
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/traces]

        metrics:
          receivers: [otlp]
          exporters: [prometheus]

        #logs:
          #receivers: [otlp]
          #exporters: [otlphttp/logs]
          #exporters: [debug]
