apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-service
  template:
    metadata:
      labels:
        app: package-service
    spec:
      containers:
      - name: package-service
        image: your-docker-repo/package-service:latest
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: package-service
spec:
  selector:
    app: package-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
  type: ClusterIP