// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: package_service.proto
// Protobuf C++ Version: 6.30.0

#ifndef package_5fservice_2eproto_2epb_2eh
#define package_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_package_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_package_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_package_5fservice_2eproto;
}  // extern "C"
namespace package {
enum PackageStatus : int;
extern const uint32_t PackageStatus_internal_data_[];
class DeliveredCount;
struct DeliveredCountDefaultTypeInternal;
extern DeliveredCountDefaultTypeInternal _DeliveredCount_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DeliveredCount_class_data_;
class PackageData;
struct PackageDataDefaultTypeInternal;
extern PackageDataDefaultTypeInternal _PackageData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageData_class_data_;
class PackageInstruction;
struct PackageInstructionDefaultTypeInternal;
extern PackageInstructionDefaultTypeInternal _PackageInstruction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageInstruction_class_data_;
class PackageResponse;
struct PackageResponseDefaultTypeInternal;
extern PackageResponseDefaultTypeInternal _PackageResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageResponse_class_data_;
class PackageStatusRequest;
struct PackageStatusRequestDefaultTypeInternal;
extern PackageStatusRequestDefaultTypeInternal _PackageStatusRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageStatusRequest_class_data_;
class PackageStatusResponse;
struct PackageStatusResponseDefaultTypeInternal;
extern PackageStatusResponseDefaultTypeInternal _PackageStatusResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageStatusResponse_class_data_;
class PackageUpdate;
struct PackageUpdateDefaultTypeInternal;
extern PackageUpdateDefaultTypeInternal _PackageUpdate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PackageUpdate_class_data_;
class VehicleQuery;
struct VehicleQueryDefaultTypeInternal;
extern VehicleQueryDefaultTypeInternal _VehicleQuery_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VehicleQuery_class_data_;
}  // namespace package
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::package::PackageStatus_internal_data_>
    internal::EnumTraitsImpl::value<::package::PackageStatus>;
}  // namespace protobuf
}  // namespace google

namespace package {
enum PackageStatus : int {
  CREATED = 0,
  IN_TRANSIT = 1,
  DELIVERED = 2,
  PackageStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PackageStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PackageStatus_internal_data_[];
inline constexpr PackageStatus PackageStatus_MIN =
    static_cast<PackageStatus>(0);
inline constexpr PackageStatus PackageStatus_MAX =
    static_cast<PackageStatus>(2);
inline bool PackageStatus_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int PackageStatus_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PackageStatus_descriptor();
template <typename T>
const std::string& PackageStatus_Name(T value) {
  static_assert(std::is_same<T, PackageStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PackageStatus_Name().");
  return PackageStatus_Name(static_cast<PackageStatus>(value));
}
template <>
inline const std::string& PackageStatus_Name(PackageStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PackageStatus_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool PackageStatus_Parse(
    absl::string_view name, PackageStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PackageStatus>(PackageStatus_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class VehicleQuery final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.VehicleQuery) */ {
 public:
  inline VehicleQuery() : VehicleQuery(nullptr) {}
  ~VehicleQuery() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VehicleQuery* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VehicleQuery));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VehicleQuery(::google::protobuf::internal::ConstantInitialized);

  inline VehicleQuery(const VehicleQuery& from) : VehicleQuery(nullptr, from) {}
  inline VehicleQuery(VehicleQuery&& from) noexcept
      : VehicleQuery(nullptr, std::move(from)) {}
  inline VehicleQuery& operator=(const VehicleQuery& from) {
    CopyFrom(from);
    return *this;
  }
  inline VehicleQuery& operator=(VehicleQuery&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VehicleQuery& default_instance() {
    return *reinterpret_cast<const VehicleQuery*>(
        &_VehicleQuery_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(VehicleQuery& a, VehicleQuery& b) { a.Swap(&b); }
  inline void Swap(VehicleQuery* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VehicleQuery* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VehicleQuery* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VehicleQuery>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VehicleQuery& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VehicleQuery& from) { VehicleQuery::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VehicleQuery* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.VehicleQuery"; }

 protected:
  explicit VehicleQuery(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VehicleQuery(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VehicleQuery& from);
  VehicleQuery(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VehicleQuery&& from) noexcept
      : VehicleQuery(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVehicleIdFieldNumber = 1,
  };
  // int32 vehicle_id = 1;
  void clear_vehicle_id() ;
  ::int32_t vehicle_id() const;
  void set_vehicle_id(::int32_t value);

  private:
  ::int32_t _internal_vehicle_id() const;
  void _internal_set_vehicle_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:package.VehicleQuery)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VehicleQuery& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t vehicle_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull VehicleQuery_class_data_;
// -------------------------------------------------------------------

class PackageUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageUpdate) */ {
 public:
  inline PackageUpdate() : PackageUpdate(nullptr) {}
  ~PackageUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageUpdate* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageUpdate(::google::protobuf::internal::ConstantInitialized);

  inline PackageUpdate(const PackageUpdate& from) : PackageUpdate(nullptr, from) {}
  inline PackageUpdate(PackageUpdate&& from) noexcept
      : PackageUpdate(nullptr, std::move(from)) {}
  inline PackageUpdate& operator=(const PackageUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageUpdate& operator=(PackageUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageUpdate& default_instance() {
    return *reinterpret_cast<const PackageUpdate*>(
        &_PackageUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PackageUpdate& a, PackageUpdate& b) { a.Swap(&b); }
  inline void Swap(PackageUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageUpdate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageUpdate& from) { PackageUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageUpdate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageUpdate"; }

 protected:
  explicit PackageUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageUpdate& from);
  PackageUpdate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageUpdate&& from) noexcept
      : PackageUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVehicleIdFieldNumber = 1,
    kPackageIdFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // int32 vehicle_id = 1;
  void clear_vehicle_id() ;
  ::int32_t vehicle_id() const;
  void set_vehicle_id(::int32_t value);

  private:
  ::int32_t _internal_vehicle_id() const;
  void _internal_set_vehicle_id(::int32_t value);

  public:
  // int32 package_id = 2;
  void clear_package_id() ;
  ::int32_t package_id() const;
  void set_package_id(::int32_t value);

  private:
  ::int32_t _internal_package_id() const;
  void _internal_set_package_id(::int32_t value);

  public:
  // .package.PackageStatus status = 3;
  void clear_status() ;
  ::package::PackageStatus status() const;
  void set_status(::package::PackageStatus value);

  private:
  ::package::PackageStatus _internal_status() const;
  void _internal_set_status(::package::PackageStatus value);

  public:
  // @@protoc_insertion_point(class_scope:package.PackageUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageUpdate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t vehicle_id_;
    ::int32_t package_id_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageUpdate_class_data_;
// -------------------------------------------------------------------

class PackageStatusResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageStatusResponse) */ {
 public:
  inline PackageStatusResponse() : PackageStatusResponse(nullptr) {}
  ~PackageStatusResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageStatusResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageStatusResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageStatusResponse(::google::protobuf::internal::ConstantInitialized);

  inline PackageStatusResponse(const PackageStatusResponse& from) : PackageStatusResponse(nullptr, from) {}
  inline PackageStatusResponse(PackageStatusResponse&& from) noexcept
      : PackageStatusResponse(nullptr, std::move(from)) {}
  inline PackageStatusResponse& operator=(const PackageStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageStatusResponse& operator=(PackageStatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageStatusResponse& default_instance() {
    return *reinterpret_cast<const PackageStatusResponse*>(
        &_PackageStatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(PackageStatusResponse& a, PackageStatusResponse& b) { a.Swap(&b); }
  inline void Swap(PackageStatusResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageStatusResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageStatusResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageStatusResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageStatusResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageStatusResponse& from) { PackageStatusResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageStatusResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageStatusResponse"; }

 protected:
  explicit PackageStatusResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageStatusResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageStatusResponse& from);
  PackageStatusResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageStatusResponse&& from) noexcept
      : PackageStatusResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .package.PackageStatus status = 1;
  void clear_status() ;
  ::package::PackageStatus status() const;
  void set_status(::package::PackageStatus value);

  private:
  ::package::PackageStatus _internal_status() const;
  void _internal_set_status(::package::PackageStatus value);

  public:
  // @@protoc_insertion_point(class_scope:package.PackageStatusResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageStatusResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageStatusResponse_class_data_;
// -------------------------------------------------------------------

class PackageStatusRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageStatusRequest) */ {
 public:
  inline PackageStatusRequest() : PackageStatusRequest(nullptr) {}
  ~PackageStatusRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageStatusRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageStatusRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageStatusRequest(::google::protobuf::internal::ConstantInitialized);

  inline PackageStatusRequest(const PackageStatusRequest& from) : PackageStatusRequest(nullptr, from) {}
  inline PackageStatusRequest(PackageStatusRequest&& from) noexcept
      : PackageStatusRequest(nullptr, std::move(from)) {}
  inline PackageStatusRequest& operator=(const PackageStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageStatusRequest& operator=(PackageStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageStatusRequest& default_instance() {
    return *reinterpret_cast<const PackageStatusRequest*>(
        &_PackageStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PackageStatusRequest& a, PackageStatusRequest& b) { a.Swap(&b); }
  inline void Swap(PackageStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageStatusRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageStatusRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageStatusRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageStatusRequest& from) { PackageStatusRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageStatusRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageStatusRequest"; }

 protected:
  explicit PackageStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageStatusRequest& from);
  PackageStatusRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageStatusRequest&& from) noexcept
      : PackageStatusRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPackageIdFieldNumber = 1,
  };
  // int32 package_id = 1;
  void clear_package_id() ;
  ::int32_t package_id() const;
  void set_package_id(::int32_t value);

  private:
  ::int32_t _internal_package_id() const;
  void _internal_set_package_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:package.PackageStatusRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageStatusRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t package_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageStatusRequest_class_data_;
// -------------------------------------------------------------------

class PackageResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageResponse) */ {
 public:
  inline PackageResponse() : PackageResponse(nullptr) {}
  ~PackageResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageResponse(::google::protobuf::internal::ConstantInitialized);

  inline PackageResponse(const PackageResponse& from) : PackageResponse(nullptr, from) {}
  inline PackageResponse(PackageResponse&& from) noexcept
      : PackageResponse(nullptr, std::move(from)) {}
  inline PackageResponse& operator=(const PackageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageResponse& operator=(PackageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageResponse& default_instance() {
    return *reinterpret_cast<const PackageResponse*>(
        &_PackageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PackageResponse& a, PackageResponse& b) { a.Swap(&b); }
  inline void Swap(PackageResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageResponse& from) { PackageResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageResponse"; }

 protected:
  explicit PackageResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageResponse& from);
  PackageResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageResponse&& from) noexcept
      : PackageResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPackageIdFieldNumber = 1,
  };
  // int32 package_id = 1;
  void clear_package_id() ;
  ::int32_t package_id() const;
  void set_package_id(::int32_t value);

  private:
  ::int32_t _internal_package_id() const;
  void _internal_set_package_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:package.PackageResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t package_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageResponse_class_data_;
// -------------------------------------------------------------------

class PackageInstruction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageInstruction) */ {
 public:
  inline PackageInstruction() : PackageInstruction(nullptr) {}
  ~PackageInstruction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageInstruction* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageInstruction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageInstruction(::google::protobuf::internal::ConstantInitialized);

  inline PackageInstruction(const PackageInstruction& from) : PackageInstruction(nullptr, from) {}
  inline PackageInstruction(PackageInstruction&& from) noexcept
      : PackageInstruction(nullptr, std::move(from)) {}
  inline PackageInstruction& operator=(const PackageInstruction& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageInstruction& operator=(PackageInstruction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageInstruction& default_instance() {
    return *reinterpret_cast<const PackageInstruction*>(
        &_PackageInstruction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PackageInstruction& a, PackageInstruction& b) { a.Swap(&b); }
  inline void Swap(PackageInstruction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageInstruction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageInstruction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageInstruction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageInstruction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageInstruction& from) { PackageInstruction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageInstruction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageInstruction"; }

 protected:
  explicit PackageInstruction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageInstruction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageInstruction& from);
  PackageInstruction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageInstruction&& from) noexcept
      : PackageInstruction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDeliveryAddressFieldNumber = 2,
    kPackageIdFieldNumber = 1,
  };
  // string delivery_address = 2;
  void clear_delivery_address() ;
  const std::string& delivery_address() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_delivery_address(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_delivery_address();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_delivery_address();
  void set_allocated_delivery_address(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_delivery_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_delivery_address(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_delivery_address();

  public:
  // int32 package_id = 1;
  void clear_package_id() ;
  ::int32_t package_id() const;
  void set_package_id(::int32_t value);

  private:
  ::int32_t _internal_package_id() const;
  void _internal_set_package_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:package.PackageInstruction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 51,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageInstruction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr delivery_address_;
    ::int32_t package_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageInstruction_class_data_;
// -------------------------------------------------------------------

class PackageData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.PackageData) */ {
 public:
  inline PackageData() : PackageData(nullptr) {}
  ~PackageData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackageData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackageData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PackageData(::google::protobuf::internal::ConstantInitialized);

  inline PackageData(const PackageData& from) : PackageData(nullptr, from) {}
  inline PackageData(PackageData&& from) noexcept
      : PackageData(nullptr, std::move(from)) {}
  inline PackageData& operator=(const PackageData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageData& operator=(PackageData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageData& default_instance() {
    return *reinterpret_cast<const PackageData*>(
        &_PackageData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PackageData& a, PackageData& b) { a.Swap(&b); }
  inline void Swap(PackageData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PackageData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PackageData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PackageData& from) { PackageData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackageData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.PackageData"; }

 protected:
  explicit PackageData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackageData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackageData& from);
  PackageData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackageData&& from) noexcept
      : PackageData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSenderAddressFieldNumber = 1,
    kRecipientAddressFieldNumber = 2,
  };
  // string sender_address = 1;
  void clear_sender_address() ;
  const std::string& sender_address() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sender_address(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_sender_address();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_sender_address();
  void set_allocated_sender_address(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_sender_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender_address(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_sender_address();

  public:
  // string recipient_address = 2;
  void clear_recipient_address() ;
  const std::string& recipient_address() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_recipient_address(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_recipient_address();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_recipient_address();
  void set_allocated_recipient_address(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_recipient_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_recipient_address(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_recipient_address();

  public:
  // @@protoc_insertion_point(class_scope:package.PackageData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 59,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackageData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sender_address_;
    ::google::protobuf::internal::ArenaStringPtr recipient_address_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PackageData_class_data_;
// -------------------------------------------------------------------

class DeliveredCount final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:package.DeliveredCount) */ {
 public:
  inline DeliveredCount() : DeliveredCount(nullptr) {}
  ~DeliveredCount() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DeliveredCount* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DeliveredCount));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DeliveredCount(::google::protobuf::internal::ConstantInitialized);

  inline DeliveredCount(const DeliveredCount& from) : DeliveredCount(nullptr, from) {}
  inline DeliveredCount(DeliveredCount&& from) noexcept
      : DeliveredCount(nullptr, std::move(from)) {}
  inline DeliveredCount& operator=(const DeliveredCount& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeliveredCount& operator=(DeliveredCount&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeliveredCount& default_instance() {
    return *reinterpret_cast<const DeliveredCount*>(
        &_DeliveredCount_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(DeliveredCount& a, DeliveredCount& b) { a.Swap(&b); }
  inline void Swap(DeliveredCount* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeliveredCount* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeliveredCount* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DeliveredCount>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DeliveredCount& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DeliveredCount& from) { DeliveredCount::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DeliveredCount* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "package.DeliveredCount"; }

 protected:
  explicit DeliveredCount(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DeliveredCount(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DeliveredCount& from);
  DeliveredCount(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DeliveredCount&& from) noexcept
      : DeliveredCount(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCountFieldNumber = 1,
  };
  // int32 count = 1;
  void clear_count() ;
  ::int32_t count() const;
  void set_count(::int32_t value);

  private:
  ::int32_t _internal_count() const;
  void _internal_set_count(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:package.DeliveredCount)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DeliveredCount& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DeliveredCount_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PackageUpdate

// int32 vehicle_id = 1;
inline void PackageUpdate::clear_vehicle_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PackageUpdate::vehicle_id() const {
  // @@protoc_insertion_point(field_get:package.PackageUpdate.vehicle_id)
  return _internal_vehicle_id();
}
inline void PackageUpdate::set_vehicle_id(::int32_t value) {
  _internal_set_vehicle_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.PackageUpdate.vehicle_id)
}
inline ::int32_t PackageUpdate::_internal_vehicle_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vehicle_id_;
}
inline void PackageUpdate::_internal_set_vehicle_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_id_ = value;
}

// int32 package_id = 2;
inline void PackageUpdate::clear_package_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PackageUpdate::package_id() const {
  // @@protoc_insertion_point(field_get:package.PackageUpdate.package_id)
  return _internal_package_id();
}
inline void PackageUpdate::set_package_id(::int32_t value) {
  _internal_set_package_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:package.PackageUpdate.package_id)
}
inline ::int32_t PackageUpdate::_internal_package_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_id_;
}
inline void PackageUpdate::_internal_set_package_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = value;
}

// .package.PackageStatus status = 3;
inline void PackageUpdate::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::package::PackageStatus PackageUpdate::status() const {
  // @@protoc_insertion_point(field_get:package.PackageUpdate.status)
  return _internal_status();
}
inline void PackageUpdate::set_status(::package::PackageStatus value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:package.PackageUpdate.status)
}
inline ::package::PackageStatus PackageUpdate::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::package::PackageStatus>(_impl_.status_);
}
inline void PackageUpdate::_internal_set_status(::package::PackageStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// -------------------------------------------------------------------

// PackageInstruction

// int32 package_id = 1;
inline void PackageInstruction::clear_package_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t PackageInstruction::package_id() const {
  // @@protoc_insertion_point(field_get:package.PackageInstruction.package_id)
  return _internal_package_id();
}
inline void PackageInstruction::set_package_id(::int32_t value) {
  _internal_set_package_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:package.PackageInstruction.package_id)
}
inline ::int32_t PackageInstruction::_internal_package_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_id_;
}
inline void PackageInstruction::_internal_set_package_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = value;
}

// string delivery_address = 2;
inline void PackageInstruction::clear_delivery_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delivery_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PackageInstruction::delivery_address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:package.PackageInstruction.delivery_address)
  return _internal_delivery_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PackageInstruction::set_delivery_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.delivery_address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:package.PackageInstruction.delivery_address)
}
inline std::string* PROTOBUF_NONNULL PackageInstruction::mutable_delivery_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_delivery_address();
  // @@protoc_insertion_point(field_mutable:package.PackageInstruction.delivery_address)
  return _s;
}
inline const std::string& PackageInstruction::_internal_delivery_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.delivery_address_.Get();
}
inline void PackageInstruction::_internal_set_delivery_address(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.delivery_address_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PackageInstruction::_internal_mutable_delivery_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.delivery_address_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PackageInstruction::release_delivery_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:package.PackageInstruction.delivery_address)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.delivery_address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.delivery_address_.Set("", GetArena());
  }
  return released;
}
inline void PackageInstruction::set_allocated_delivery_address(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.delivery_address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.delivery_address_.IsDefault()) {
    _impl_.delivery_address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:package.PackageInstruction.delivery_address)
}

// -------------------------------------------------------------------

// PackageData

// string sender_address = 1;
inline void PackageData::clear_sender_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PackageData::sender_address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:package.PackageData.sender_address)
  return _internal_sender_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PackageData::set_sender_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sender_address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:package.PackageData.sender_address)
}
inline std::string* PROTOBUF_NONNULL PackageData::mutable_sender_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sender_address();
  // @@protoc_insertion_point(field_mutable:package.PackageData.sender_address)
  return _s;
}
inline const std::string& PackageData::_internal_sender_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_address_.Get();
}
inline void PackageData::_internal_set_sender_address(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sender_address_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PackageData::_internal_mutable_sender_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.sender_address_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PackageData::release_sender_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:package.PackageData.sender_address)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.sender_address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sender_address_.Set("", GetArena());
  }
  return released;
}
inline void PackageData::set_allocated_sender_address(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.sender_address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sender_address_.IsDefault()) {
    _impl_.sender_address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:package.PackageData.sender_address)
}

// string recipient_address = 2;
inline void PackageData::clear_recipient_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recipient_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PackageData::recipient_address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:package.PackageData.recipient_address)
  return _internal_recipient_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PackageData::set_recipient_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.recipient_address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:package.PackageData.recipient_address)
}
inline std::string* PROTOBUF_NONNULL PackageData::mutable_recipient_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_recipient_address();
  // @@protoc_insertion_point(field_mutable:package.PackageData.recipient_address)
  return _s;
}
inline const std::string& PackageData::_internal_recipient_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.recipient_address_.Get();
}
inline void PackageData::_internal_set_recipient_address(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.recipient_address_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL PackageData::_internal_mutable_recipient_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.recipient_address_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE PackageData::release_recipient_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:package.PackageData.recipient_address)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.recipient_address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.recipient_address_.Set("", GetArena());
  }
  return released;
}
inline void PackageData::set_allocated_recipient_address(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.recipient_address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.recipient_address_.IsDefault()) {
    _impl_.recipient_address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:package.PackageData.recipient_address)
}

// -------------------------------------------------------------------

// PackageResponse

// int32 package_id = 1;
inline void PackageResponse::clear_package_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PackageResponse::package_id() const {
  // @@protoc_insertion_point(field_get:package.PackageResponse.package_id)
  return _internal_package_id();
}
inline void PackageResponse::set_package_id(::int32_t value) {
  _internal_set_package_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.PackageResponse.package_id)
}
inline ::int32_t PackageResponse::_internal_package_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_id_;
}
inline void PackageResponse::_internal_set_package_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = value;
}

// -------------------------------------------------------------------

// PackageStatusRequest

// int32 package_id = 1;
inline void PackageStatusRequest::clear_package_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t PackageStatusRequest::package_id() const {
  // @@protoc_insertion_point(field_get:package.PackageStatusRequest.package_id)
  return _internal_package_id();
}
inline void PackageStatusRequest::set_package_id(::int32_t value) {
  _internal_set_package_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.PackageStatusRequest.package_id)
}
inline ::int32_t PackageStatusRequest::_internal_package_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_id_;
}
inline void PackageStatusRequest::_internal_set_package_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_id_ = value;
}

// -------------------------------------------------------------------

// PackageStatusResponse

// .package.PackageStatus status = 1;
inline void PackageStatusResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::package::PackageStatus PackageStatusResponse::status() const {
  // @@protoc_insertion_point(field_get:package.PackageStatusResponse.status)
  return _internal_status();
}
inline void PackageStatusResponse::set_status(::package::PackageStatus value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.PackageStatusResponse.status)
}
inline ::package::PackageStatus PackageStatusResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::package::PackageStatus>(_impl_.status_);
}
inline void PackageStatusResponse::_internal_set_status(::package::PackageStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// -------------------------------------------------------------------

// VehicleQuery

// int32 vehicle_id = 1;
inline void VehicleQuery::clear_vehicle_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t VehicleQuery::vehicle_id() const {
  // @@protoc_insertion_point(field_get:package.VehicleQuery.vehicle_id)
  return _internal_vehicle_id();
}
inline void VehicleQuery::set_vehicle_id(::int32_t value) {
  _internal_set_vehicle_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.VehicleQuery.vehicle_id)
}
inline ::int32_t VehicleQuery::_internal_vehicle_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vehicle_id_;
}
inline void VehicleQuery::_internal_set_vehicle_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_id_ = value;
}

// -------------------------------------------------------------------

// DeliveredCount

// int32 count = 1;
inline void DeliveredCount::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t DeliveredCount::count() const {
  // @@protoc_insertion_point(field_get:package.DeliveredCount.count)
  return _internal_count();
}
inline void DeliveredCount::set_count(::int32_t value) {
  _internal_set_count(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:package.DeliveredCount.count)
}
inline ::int32_t DeliveredCount::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void DeliveredCount::_internal_set_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace package


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::package::PackageStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::package::PackageStatus>() {
  return ::package::PackageStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // package_5fservice_2eproto_2epb_2eh
